services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/certs:/etc/nginx/certs:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.nginx-proxy.nginx
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    volumes:
      - ./config/acme:/etc/acme.sh
      - ./config/nginx/certs:/etc/nginx/certs
      - ./config/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
